// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'article': string;
  'container': string;
  'headline': string;
  'image': string;
  'imageCredit': string;
  'leadingParagraph': string;
  'redBox': string;
  'whyChooseUsBox': string;
  'whyChooseUsHeadline': string;
  'whyChooseUsList': string;
  'whyChooseUsListItem': string;
}
declare var cssExports: CssExports;
export = cssExports;
